name: Python Script Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # 1 AM Taipei time (5 AM UTC)
    - cron: '0 11 * * *' # 7 PM Taipei time (11 AM UTC)
    - cron: '0 12 * * *' # 8 PM Taipei time (12 PM UTC)

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Taipei"  # Set the desired timezone here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt  # Install packages from requirements.txt

      - name: Execute Python script
        run: |
          set -e
          python ./src/daily_update.py

      - name: Commit files
        run: |
          git config --local user.email "aplusman@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Run workflow on $(date +'%I %p on %m-%d-%Y')" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
